from __future__ import annotations

import json
from pathlib import Path

import unittest

from runtime import native_kernel_scheduler_smp as scheduler_smp
from tools import pooleos_release_gate


ROOT = Path(__file__).resolve().parents[1]


def _raises(error: type[BaseException]):
    return unittest.TestCase().assertRaises(error)


def _skip(reason: str) -> None:
    raise unittest.SkipTest(reason)


def load_tests(loader, standard_tests, pattern):
    suite = unittest.TestSuite()
    for name, value in sorted(globals().items()):
        if name.startswith("test_") and callable(value):
            suite.addTest(unittest.FunctionTestCase(value, description=name))
    return suite


def _probe_lines() -> list[str]:
    return [
        "PKSCHED4:TOPOLOGY PASS cpus=4 online_mask=0x0F ap_mask=0x0E queues=4 tasks=8 balance=3,3 idle_owners=4",
        "PKSCHED4:TRANSFER PASS wake=1 migrations=2 transaction_acks=3 queues=2,2,2 owner_transfer=ack_gated timeout_target=4",
        "PKSCHED4:DISPATCH PASS bsp_trace=0,7 ap_trace=1:2,1:1,2:4,2:3,3:6,3:5 bsp_dispatches=2 ap_dispatches=6 ipi_acks=9 call_function_executions=9 max_bypass=1",
        "PKSCHED4:ROLLBACK PASS offline_cpu=4 timeouts=1 rollbacks=1 late_ack_rejected=1 stale_generation_rejected=1 stale_rejections=2 lost_wake=0 duplicate_runnable=0",
        "PKSCHED4:CLEANUP PASS tasks_dead=8 queues=0 running=0 idle_before=4 owner_epoch_sum=19 online_after=0x01 parked_mask=0x0E teardown=8 valid=1",
    ]


def test_contract_matches_schema_controls_and_claims() -> None:
    contract = scheduler_smp.read_json(ROOT / scheduler_smp.CONTRACT_RELATIVE)
    assert scheduler_smp.contract_errors(contract, ROOT) == []
    assert len(contract["required_negative_controls"]) == 32
    assert contract["claims"] == scheduler_smp.expected_claims()


def test_independent_oracle_has_exact_bounded_trace() -> None:
    assert scheduler_smp.trace_oracle() == {
        "balance": (3, 3),
        "queues_after_transfer": (2, 2, 2),
        "bsp_trace": (0, 7),
        "ap_trace": ((1, 2), (1, 1), (2, 4), (2, 3), (3, 6), (3, 5)),
        "owner_epoch_sum": 19,
        "remote_acks": 9,
        "maximum_bypass": 1,
    }


def test_probe_parser_accepts_only_exact_receipts() -> None:
    parsed = scheduler_smp.parse_probe_output("\n".join(_probe_lines()) + "\n")
    assert parsed["receipt_count"] == 5
    assert parsed["rust_python_exact_agreement"] is True
    for index in range(5):
        hostile = _probe_lines()
        hostile.pop(index)
        with _raises(scheduler_smp.KernelSchedulerSmpError):
            scheduler_smp.parse_probe_output("\n".join(hostile) + "\n")


def test_probe_parser_rejects_trace_ack_and_cleanup_drift() -> None:
    for index, old, new in [
        (0, "balance=3,3", "balance=2,3"),
        (1, "transaction_acks=3", "transaction_acks=2"),
        (2, "ap_trace=1:2", "ap_trace=1:1"),
        (3, "rollbacks=1", "rollbacks=0"),
        (4, "owner_epoch_sum=19", "owner_epoch_sum=18"),
    ]:
        hostile = _probe_lines()
        hostile[index] = hostile[index].replace(old, new)
        with _raises(scheduler_smp.KernelSchedulerSmpError):
            scheduler_smp.parse_probe_output("\n".join(hostile) + "\n")


def test_input_binding_rejects_escape_and_is_complete() -> None:
    inputs = scheduler_smp.expected_inputs(ROOT)
    assert len(inputs["implementation"]) == len(scheduler_smp.IMPLEMENTATION_INPUTS)
    with _raises(scheduler_smp.KernelSchedulerSmpError):
        scheduler_smp.file_binding(ROOT, "../outside")


def test_readiness_schema_rejects_promotion() -> None:
    schema = scheduler_smp.read_json(ROOT / scheduler_smp.READINESS_SCHEMA_RELATIVE)
    assert schema["properties"]["production_ready"] == {"const": False}
    assert schema["properties"]["production_promotion_allowed"] == {"const": False}
    contract = json.loads((ROOT / scheduler_smp.CONTRACT_RELATIVE).read_text(encoding="utf-8"))
    assert contract["production_ready"] is False


def test_release_gate_accepts_only_the_bound_non_promoting_receipt() -> None:
    path = ROOT / scheduler_smp.READINESS_RELATIVE
    if not path.is_file():
        _skip("readiness is generated by the qualifier")
    check = pooleos_release_gate.check_native_kernel_scheduler_smp_readiness(path)
    assert check["ok"], check["detail"]
