from __future__ import annotations

import json
from pathlib import Path

import unittest

from runtime import native_kernel_scheduler_deferred as deferred
from tools import pooleos_release_gate


ROOT = Path(__file__).resolve().parents[1]


def _raises(error: type[BaseException]):
    return unittest.TestCase().assertRaises(error)


def _skip(reason: str) -> None:
    raise unittest.SkipTest(reason)


def load_tests(loader, standard_tests, pattern):
    suite = unittest.TestSuite()
    for name, value in sorted(globals().items()):
        if name.startswith("test_") and callable(value):
            suite.addTest(unittest.FunctionTestCase(value, description=name))
    return suite


def _probe_lines() -> list[str]:
    return [
        "PKSCHED3:QUEUE PASS enqueued=8 duplicate=1 queued_cancelled=1 eoi=1 pending=7 flush_before=0",
        "PKSCHED3:WORK PASS slots=0,2,4,1,5,6 workers=0,1,0,1,0,1 states=completed,completed,completed,completed,completed,cancelled max_bypass=3",
        "PKSCHED3:FLUSH PASS watermark=8 completion=8 sum=120 xor=90 fence=0 completed=5 cancelled=3 running_cancel=1 retired=8 free=8",
        "PKSCHED3:FAULT PASS rollbacks=5 free=8 valid=1",
        "PKSCHED3:BOUNDARY PASS pre_eoi_rejected=1 recursion_rejected=1 stale_rejected=1 intake_rejected=1 arbitrary_callbacks=0",
    ]


def test_contract_matches_schema_controls_and_claims() -> None:
    contract = deferred.read_json(ROOT / deferred.CONTRACT_RELATIVE)
    assert deferred.contract_errors(contract, ROOT) == []
    assert len(contract["required_negative_controls"]) == 30
    assert contract["claims"] == deferred.expected_claims()


def test_independent_oracle_has_exact_bounded_trace() -> None:
    assert deferred.trace_oracle() == {
        "slots": (0, 2, 4, 1, 5, 6),
        "workers": (0, 1, 0, 1, 0, 1),
        "states": ("completed", "completed", "completed", "completed", "completed", "cancelled"),
        "max_bypass": 3,
        "sum": 120,
        "xor": 90,
        "fence": 0,
        "remaining_slots": (7,),
    }


def test_probe_parser_accepts_only_exact_receipts() -> None:
    parsed = deferred.parse_probe_output("\n".join(_probe_lines()) + "\n")
    assert parsed["receipt_count"] == 5
    assert parsed["rust_python_exact_agreement"] is True
    for index in range(5):
        hostile = _probe_lines()
        hostile.pop(index)
        with _raises(deferred.KernelSchedulerDeferredError):
            deferred.parse_probe_output("\n".join(hostile) + "\n")


def test_probe_parser_rejects_trace_and_boundary_drift() -> None:
    for index, old, new in [
        (1, "slots=0,2,4,1,5,6", "slots=0,2,4,5,1,6"),
        (2, "completion=8", "completion=7"),
        (3, "rollbacks=5", "rollbacks=4"),
        (4, "arbitrary_callbacks=0", "arbitrary_callbacks=1"),
    ]:
        hostile = _probe_lines()
        hostile[index] = hostile[index].replace(old, new)
        with _raises(deferred.KernelSchedulerDeferredError):
            deferred.parse_probe_output("\n".join(hostile) + "\n")


def test_input_binding_rejects_escape_and_is_complete() -> None:
    inputs = deferred.expected_inputs(ROOT)
    assert len(inputs["implementation"]) == len(deferred.IMPLEMENTATION_INPUTS)
    with _raises(deferred.KernelSchedulerDeferredError):
        deferred.file_binding(ROOT, "../outside")


def test_readiness_schema_rejects_promotion() -> None:
    schema = deferred.read_json(ROOT / deferred.READINESS_SCHEMA_RELATIVE)
    assert schema["properties"]["production_ready"] == {"const": False}
    assert schema["properties"]["production_promotion_allowed"] == {"const": False}
    assert json.loads((ROOT / deferred.CONTRACT_RELATIVE).read_text(encoding="utf-8"))["production_ready"] is False


def test_release_gate_accepts_only_the_bound_non_promoting_receipt() -> None:
    path = ROOT / deferred.READINESS_RELATIVE
    if not path.is_file():
        _skip("readiness is generated by the qualifier")
    check = pooleos_release_gate.check_native_kernel_scheduler_deferred_readiness(path)
    assert check["ok"], check["detail"]
