import copy
import contextlib
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from runtime import native_kernel_scheduler_preempt as preempt  # noqa: E402
from tools import pooleos_release_gate, qualify_native_kernel_scheduler_preempt as qualifier  # noqa: E402
from tests.test_native_kernel_scheduler import recorded_receipt_mutations  # noqa: E402


PROBE = """\
PKSCHED2:TRACE PASS ticks=6 next=0,1,2,0,3,3 causes=none,quantum,wake,block,wake,none events=0,0,1,1,1,0 runtime=3,1,1,1 switches=4 pending=0
PKSCHED2:FRAME PASS valid=1 hostile_rejected=8 top_rsp_valid=1 frame_bytes=176 alignment=16
PKSCHED2:CLEANUP PASS dead=4 runnable=0 running=0 blocked=0 teardowns=4 queue_entries=0
"""


class NativeKernelSchedulerPreemptTests(unittest.TestCase):
    def test_contract_schema_claims_and_controls_are_exact(self) -> None:
        contract = preempt.read_json(ROOT / preempt.CONTRACT_RELATIVE)
        self.assertEqual([], preempt.contract_errors(contract, ROOT))
        self.assertEqual(list(preempt.NEGATIVE_CONTROL_IDS), contract["required_negative_controls"])
        self.assertEqual(preempt.expected_claims(), contract["claims"])
        baseline = preempt.read_json(ROOT / preempt.READINESS_RELATIVE)
        for value in ("2026-09-05", "2026-09-07", "2024-02-29"):
            candidate = copy.deepcopy(baseline)
            candidate["status_date"] = value
            with self.subTest(valid_date=value):
                self.assertFalse(any("status_date" in item for item in preempt.readiness_errors(candidate, ROOT)))
        invalid_dates = (
            None, 7, True, "", "20260907", "2026-9-7", "2026-02-29",
            "2026-04-31", "2026-13-01", "2026-09-07T00:00:00",
        )
        self.assertEqual(10, len(invalid_dates))
        for value in invalid_dates:
            candidate = copy.deepcopy(baseline)
            candidate["status_date"] = value
            with self.subTest(invalid_date=value), patch.object(
                pooleos_release_gate, "_load_schema_artifact", return_value=(candidate, [])
            ):
                expected = "readiness status_date is not a canonical calendar date"
                self.assertIn(expected, preempt.readiness_errors(candidate, ROOT))
                check = pooleos_release_gate.check_native_kernel_scheduler_preemption_readiness()
                self.assertFalse(check["ok"])
                self.assertIn(expected, check["detail"])

    def test_independent_trace_oracle_is_frozen(self) -> None:
        self.assertEqual(
            {
                "ticks": 6,
                "next": (0, 1, 2, 0, 3, 3),
                "causes": ("none", "quantum", "wake", "block", "wake", "none"),
                "events": (0, 0, 1, 1, 1, 0),
                "runtime": (3, 1, 1, 1),
                "switches": 4,
                "pending": 0,
            },
            preempt.trace_oracle(),
        )

    def test_rust_probe_receipt_matches_python_oracle(self) -> None:
        receipt = preempt.parse_probe_output(PROBE)
        self.assertEqual(4, receipt["trace"]["switches"])
        self.assertEqual(8, receipt["frame_hostile_rejections"])
        self.assertEqual(4, receipt["cleanup"]["tasks_dead"])

    def test_probe_parser_rejects_omission_order_and_field_drift(self) -> None:
        lines = PROBE.splitlines()
        hostile = (
            "\n".join(lines[:-1]),
            "\n".join([lines[1], lines[0], lines[2]]),
            PROBE.replace("switches=4", "switches=3"),
            PROBE.replace("top_rsp_valid=1", "top_rsp_valid=0"),
            PROBE.replace("dead=4", "dead=3"),
        )
        for value in hostile:
            with self.assertRaises(preempt.KernelSchedulerPreemptError):
                preempt.parse_probe_output(value)

    def test_readiness_is_source_bound_and_non_promoting(self) -> None:
        path = ROOT / preempt.READINESS_RELATIVE
        if not path.is_file():
            self.skipTest("readiness is generated by the qualifier")
        readiness = preempt.read_json(path)
        self.assertEqual([], preempt.readiness_errors(readiness, ROOT))
        hostile = copy.deepcopy(readiness)
        hostile["claims"]["live_ap_scheduler_dispatch_implemented"] = True
        self.assertIn("readiness claim boundary diverges", preempt.readiness_errors(hostile, ROOT))

    def test_selector_feature_and_kernel_sources_are_wired(self) -> None:
        boot_manifest = (ROOT / "native/boot/Cargo.toml").read_text(encoding="utf-8")
        boot_exit = (ROOT / "native/boot/src/exit.rs").read_text(encoding="utf-8")
        kernel = (ROOT / "native/kernel/src/main.rs").read_text(encoding="utf-8")
        self.assertIn('development-scheduler-preempt = ["development-transfer"]', boot_manifest)
        self.assertIn('feature = "development-scheduler-preempt"', boot_exit)
        self.assertIn("DevelopmentTrapScenario::SchedulerPreempt", kernel)
        self.assertIn("dispatch_scheduler_preemption", kernel)

    def test_retained_stack_partition_preserves_map_capacities(self) -> None:
        contract = json.loads((ROOT / "specs/native-kernel-map-contract.json").read_text(encoding="utf-8"))
        layout = contract["bounded_layout"]
        self.assertEqual(192, layout["kernel_maximum_page_count"])
        self.assertEqual(36, layout["stack_page_count"])
        self.assertEqual(256, layout["handoff_page_count"])
        self.assertEqual(32, layout["ledger_a_page_capacity"])
        self.assertEqual(32, layout["ledger_b_page_capacity"])
        self.assertLess(layout["mmio_guard_high_page_index"], 1024)

    def test_recorded_evidence_corruptions_fail_runtime_and_actual_gate(self) -> None:
        baseline = preempt.read_json(ROOT / preempt.READINESS_RELATIVE)
        self.assertEqual([], preempt.readiness_errors(baseline, ROOT))
        self.assertTrue(pooleos_release_gate.check_native_kernel_scheduler_preemption_readiness()["ok"])
        count = 0
        for family, label, candidate in recorded_receipt_mutations(baseline):
            with self.subTest(family=family, label=label):
                self.assertTrue(preempt.readiness_errors(candidate, ROOT))
                with patch.object(pooleos_release_gate, "_load_schema_artifact", return_value=(candidate, [])):
                    self.assertFalse(pooleos_release_gate.check_native_kernel_scheduler_preemption_readiness()["ok"])
            count += 1
        self.assertGreaterEqual(count, 200)

    def test_executed_control_receipts_reject_shape_count_type_and_source_corruption(self) -> None:
        baseline = preempt.read_json(ROOT / preempt.READINESS_RELATIVE)
        self.assertEqual([], preempt.readiness_errors(baseline, ROOT))
        candidates = []
        for section in ("native_control_probe", "audit_controls", "source_audit", "linked_switch_audit"):
            for replacement in (None, [], {}, "invalid"):
                candidate = copy.deepcopy(baseline)
                candidate["build"][section] = replacement
                candidates.append(candidate)
        for key in baseline["build"]["native_control_probe"]:
            candidate = copy.deepcopy(baseline)
            candidate["build"]["native_control_probe"][key] = None
            candidates.append(candidate)
        for key, value in (("exit_code", False), ("hostile_cases_total", 50.0)):
            candidate = copy.deepcopy(baseline)
            candidate["build"]["native_control_probe"][key] = value
            candidates.append(candidate)
        for candidate in candidates:
            with self.subTest(candidate=candidate["build"]):
                self.assertTrue(preempt.readiness_errors(candidate, ROOT))
                with patch.object(pooleos_release_gate, "_load_schema_artifact", return_value=(candidate, [])):
                    self.assertFalse(pooleos_release_gate.check_native_kernel_scheduler_preemption_readiness()["ok"])

    def test_disabled_marker_validator_is_detected_by_controls(self) -> None:
        baseline = preempt.read_json(ROOT / preempt.READINESS_RELATIVE)
        self.assertEqual([], preempt.readiness_errors(baseline, ROOT))
        build = baseline["build"]
        with patch.object(preempt, "validate_markers", return_value=baseline["execution"]["observation"]):
            with self.assertRaises(qualifier.QualificationError):
                qualifier._negative_controls(baseline["execution"]["runs"][0]["markers"], build["host_probe"]["lines"],
                    build["source_audit"], build["linked_switch_audit"], build["native_control_probe"], build["audit_controls"])

    def test_main_rejects_invalid_report_without_creating_or_replacing_output(self) -> None:
        baseline = preempt.read_json(ROOT / preempt.READINESS_RELATIVE)
        self.assertEqual([], preempt.readiness_errors(baseline, ROOT))
        candidate = copy.deepcopy(baseline)
        candidate["execution"]["runs"][0]["qemu_exit_code"] = True
        with tempfile.TemporaryDirectory(dir=ROOT / "tmp") as temporary:
            root = Path(temporary)
            existing = root / "existing.json"
            existing.write_bytes(b"existing evidence\n")
            missing = root / "absent" / "report.json"
            for output in (existing, missing):
                with patch.object(qualifier, "make_readiness", return_value=candidate), contextlib.redirect_stdout(io.StringIO()):
                    with self.assertRaises(qualifier.QualificationError):
                        qualifier.main(["--out", str(output)])
            self.assertEqual(b"existing evidence\n", existing.read_bytes())
            self.assertFalse(missing.parent.exists())


if __name__ == "__main__":
    unittest.main()
