from __future__ import annotations

import json
from pathlib import Path

import pytest

from runtime import native_kernel_scheduler_ap_workers as ap_workers
from tools import pooleos_release_gate


ROOT = Path(__file__).resolve().parents[1]


def _probe_lines() -> list[str]:
    return [
        "PKSCHED5:TOPOLOGY PASS cpus=4 aps=3 online_mask=0x0F ap_mask=0x0E workers=3 queues=3 capacity=15 stack_bytes_each=8192",
        "PKSCHED5:QUEUE PASS enqueued=13 duplicate_suppressed=1 eoi_epoch=1 flush_watermark=13 queued_cancelled=1",
        "PKSCHED5:DISPATCH PASS trace=1:1,1:2,1:0,1:3;2:5,2:6,2:4,2:7;3:9,3:10,3:8,3:11 worker_entries=4,4,4 ap_calls=12 driver_calls=9 service_calls=3 maximum_high_bypass=2",
        "PKSCHED5:CANCEL PASS offline_cpu=4 timeouts=1 rollbacks=1 queued=1 remote_requests=1 remote_completions=1 stale_rejections=1 source_queue_restored=1",
        "PKSCHED5:FLUSH PASS complete=1 completed=11 cancelled=2 driver_sum=177 service_generation=4 reclaimed=13 stale_id_rejected=1",
        "PKSCHED5:CLEANUP PASS online_after=0x01 workers_retired=3 free=15 queued=0 dispatching=0 terminal=0 stack_bytes_cleared=24576 valid=1",
    ]


def test_contract_matches_schema_controls_and_claims() -> None:
    contract = ap_workers.read_json(ROOT / ap_workers.CONTRACT_RELATIVE)
    assert ap_workers.contract_errors(contract, ROOT) == []
    assert len(contract["required_negative_controls"]) == 34
    assert contract["claims"] == ap_workers.expected_claims()


def test_independent_oracle_has_exact_bounded_trace() -> None:
    assert ap_workers.trace_oracle() == {
        "trace": "1:1,1:2,1:0,1:3;2:5,2:6,2:4,2:7;3:9,3:10,3:8,3:11",
        "worker_entries": (4, 4, 4),
        "driver_calls": 9,
        "service_calls": 3,
        "driver_sum": 177,
        "service_generation": 4,
        "maximum_high_bypass": 2,
    }


def test_probe_parser_accepts_only_exact_receipts() -> None:
    parsed = ap_workers.parse_probe_output("\n".join(_probe_lines()) + "\n")
    assert parsed["receipt_count"] == 6
    assert parsed["rust_python_exact_agreement"] is True
    for index in range(6):
        hostile = _probe_lines()
        hostile.pop(index)
        with pytest.raises(ap_workers.KernelSchedulerApWorkersError):
            ap_workers.parse_probe_output("\n".join(hostile) + "\n")


def test_probe_parser_rejects_trace_cancel_and_cleanup_drift() -> None:
    for index, old, new in [
        (0, "workers=3", "workers=2"),
        (1, "eoi_epoch=1", "eoi_epoch=0"),
        (2, "trace=1:1", "trace=1:0"),
        (3, "rollbacks=1", "rollbacks=0"),
        (4, "reclaimed=13", "reclaimed=12"),
        (5, "stack_bytes_cleared=24576", "stack_bytes_cleared=0"),
    ]:
        hostile = _probe_lines()
        hostile[index] = hostile[index].replace(old, new)
        with pytest.raises(ap_workers.KernelSchedulerApWorkersError):
            ap_workers.parse_probe_output("\n".join(hostile) + "\n")


def test_live_serial_transcript_matches_independent_oracle_when_present() -> None:
    path = ROOT / "tmp/pksched5-debug-run-2/pooleos.serial.log"
    if not path.is_file():
        pytest.skip("local QEMU transcript is not a repository input")
    markers = ap_workers.extract_markers(path.read_bytes())
    summary = ap_workers.validate_markers(markers)
    assert len(markers) == 37
    assert summary["flush"] == {
        "completed": 11,
        "cancelled": 2,
        "reclaimed": 13,
        "driver_sum": 177,
        "service_generation": 4,
    }


def test_input_binding_rejects_escape_and_is_complete() -> None:
    inputs = ap_workers.expected_inputs(ROOT)
    assert len(inputs["implementation"]) == len(ap_workers.IMPLEMENTATION_INPUTS)
    with pytest.raises(ap_workers.KernelSchedulerApWorkersError):
        ap_workers.file_binding(ROOT, "../outside")


def test_readiness_schema_rejects_promotion() -> None:
    schema = ap_workers.read_json(ROOT / ap_workers.READINESS_SCHEMA_RELATIVE)
    assert schema["properties"]["production_ready"] == {"const": False}
    assert schema["properties"]["production_promotion_allowed"] == {"const": False}
    contract = json.loads((ROOT / ap_workers.CONTRACT_RELATIVE).read_text(encoding="utf-8"))
    assert contract["production_ready"] is False


def test_release_gate_accepts_only_the_bound_non_promoting_receipt() -> None:
    path = ROOT / ap_workers.READINESS_RELATIVE
    if not path.is_file():
        pytest.skip("readiness is generated by the qualifier")
    check = pooleos_release_gate.check_native_kernel_scheduler_ap_workers_readiness(path)
    assert check["ok"], check["detail"]
