import copy
import json
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from runtime import native_kernel_scheduler_preempt as preempt  # noqa: E402


PROBE = """\
PKSCHED2:TRACE PASS ticks=6 next=0,1,2,0,3,3 causes=none,quantum,wake,block,wake,none events=0,0,1,1,1,0 runtime=3,1,1,1 switches=4 pending=0
PKSCHED2:FRAME PASS valid=1 hostile_rejected=8 top_rsp_valid=1 frame_bytes=176 alignment=16
PKSCHED2:CLEANUP PASS dead=4 runnable=0 running=0 blocked=0 teardowns=4 queue_entries=0
"""


class NativeKernelSchedulerPreemptTests(unittest.TestCase):
    def test_contract_schema_claims_and_controls_are_exact(self) -> None:
        contract = preempt.read_json(ROOT / preempt.CONTRACT_RELATIVE)
        self.assertEqual([], preempt.contract_errors(contract, ROOT))
        self.assertEqual(list(preempt.NEGATIVE_CONTROL_IDS), contract["required_negative_controls"])
        self.assertEqual(preempt.expected_claims(), contract["claims"])

    def test_independent_trace_oracle_is_frozen(self) -> None:
        self.assertEqual(
            {
                "ticks": 6,
                "next": (0, 1, 2, 0, 3, 3),
                "causes": ("none", "quantum", "wake", "block", "wake", "none"),
                "events": (0, 0, 1, 1, 1, 0),
                "runtime": (3, 1, 1, 1),
                "switches": 4,
                "pending": 0,
            },
            preempt.trace_oracle(),
        )

    def test_rust_probe_receipt_matches_python_oracle(self) -> None:
        receipt = preempt.parse_probe_output(PROBE)
        self.assertEqual(4, receipt["trace"]["switches"])
        self.assertEqual(8, receipt["frame_hostile_rejections"])
        self.assertEqual(4, receipt["cleanup"]["tasks_dead"])

    def test_probe_parser_rejects_omission_order_and_field_drift(self) -> None:
        lines = PROBE.splitlines()
        hostile = (
            "\n".join(lines[:-1]),
            "\n".join([lines[1], lines[0], lines[2]]),
            PROBE.replace("switches=4", "switches=3"),
            PROBE.replace("top_rsp_valid=1", "top_rsp_valid=0"),
            PROBE.replace("dead=4", "dead=3"),
        )
        for value in hostile:
            with self.assertRaises(preempt.KernelSchedulerPreemptError):
                preempt.parse_probe_output(value)

    def test_readiness_is_source_bound_and_non_promoting(self) -> None:
        path = ROOT / preempt.READINESS_RELATIVE
        if not path.is_file():
            self.skipTest("readiness is generated by the qualifier")
        readiness = preempt.read_json(path)
        self.assertEqual([], preempt.readiness_errors(readiness, ROOT))
        hostile = copy.deepcopy(readiness)
        hostile["claims"]["live_ap_scheduler_dispatch_implemented"] = True
        self.assertIn("readiness claim boundary diverges", preempt.readiness_errors(hostile, ROOT))

    def test_selector_feature_and_kernel_sources_are_wired(self) -> None:
        boot_manifest = (ROOT / "native/boot/Cargo.toml").read_text(encoding="utf-8")
        boot_exit = (ROOT / "native/boot/src/exit.rs").read_text(encoding="utf-8")
        kernel = (ROOT / "native/kernel/src/main.rs").read_text(encoding="utf-8")
        self.assertIn('development-scheduler-preempt = ["development-transfer"]', boot_manifest)
        self.assertIn('feature = "development-scheduler-preempt"', boot_exit)
        self.assertIn("DevelopmentTrapScenario::SchedulerPreempt", kernel)
        self.assertIn("dispatch_scheduler_preemption", kernel)

    def test_retained_stack_partition_preserves_map_capacities(self) -> None:
        contract = json.loads((ROOT / "specs/native-kernel-map-contract.json").read_text(encoding="utf-8"))
        layout = contract["bounded_layout"]
        self.assertEqual(143, layout["kernel_maximum_page_count"])
        self.assertEqual(36, layout["stack_page_count"])
        self.assertEqual(256, layout["handoff_page_count"])
        self.assertEqual(32, layout["ledger_a_page_capacity"])
        self.assertEqual(32, layout["ledger_b_page_capacity"])
        self.assertLess(layout["mmio_guard_high_page_index"], 1024)


if __name__ == "__main__":
    unittest.main()
